module.exports = {
  AIRTABLE_APIKEY:
    'patHbwcfkRmGgm0cj.05eb09cd5198428158e0ce5711eabd38d7f139eadb10bc57168a3eba6ee70e8c',
  AIRTABLE_BASEID: 'appkch0eFPEVvBjWG',
  GENRES: [
    'All',
    'Hip Hop/Rap',
    '',
    'Pop',
    ' R&B',
    'Alternative',
    'RandB',
    ' Alternative',
    ' Rock',
    'Rock',
    ' Folk',
    ' Cover',
    'EDM',
    ' Pop',
    'R&B/Soul',
    'Label',
    ' Blog',
    'S/S',
    ' Country',
    'Country',
    'Latin',
    ' EDM',
    'Reggae',
    'Instrumental',
    ' Instrumental',
    ' Hip Hop/Rap',
    'R&B',
    'LABEL',
    ' RandB',
    'World',
    'Metal',
    ' Covers',
    ' Pop ',
    'Blog',
    ' Podcast',
    'Dance',
    ' R&B/Soul',
  ],
};
